server:
  port: 8088

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: notification-application-status
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        "[spring.json.value.default.type]": com.tbm.recruitment.notification.event.ApplicationStatusChangedEvent
        "[spring.json.trusted.packages]": com.tbm.recruitment.notification.event
        "[spring.json.use.type.headers]": false

  mongodb:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    database: ${NOTIFICATION_MONGO_DATABASE:notification_db}
    username: ${MONGO_ROOT_USERNAME:root}
    password: ${MONGO_ROOT_PASSWORD:root123456}
    authentication-database: admin
    representation:
      uuid: standard
services:
  candidate:
    base-url: ${CANDIDATE_SERVICE_URL:http://localhost:8082}

app:
  kafka:
    topics:
      application-status-changed: application.status.changed
      interview-scheduled: interview.scheduled