import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { getApiErrorMessage } from '../services/apiError'
import { createJob, getOwnedJob, updateJob } from '../services/jobService'

const educationLevels = ['NONE', 'HIGH_SCHOOL', 'DIPLOMA', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORATE']
const emptyJob = { title: '', description: '', requirements: '', requiredSkills: '', minimumYearsExperience: 0, requiredEducationLevel: 'NONE', domain: '', location: '', employmentType: '', workplaceType: '', salaryMin: '', salaryMax: '' }

function RecruiterJobFormPage() {
  const { jobId } = useParams(); const navigate = useNavigate(); const [form, setForm] = useState(emptyJob); const [isLoading, setIsLoading] = useState(Boolean(jobId)); const [isSaving, setIsSaving] = useState(false); const [error, setError] = useState('')
  useEffect(() => { if (!jobId) return; getOwnedJob(jobId).then((job) => setForm({ ...job, requiredSkills: (job.requiredSkills || []).join(', '), salaryMin: job.salaryMin || '', salaryMax: job.salaryMax || '' })).catch((requestError) => setError(getApiErrorMessage(requestError, 'Unable to load this job.'))).finally(() => setIsLoading(false)) }, [jobId])
  function updateField(event) { setForm({ ...form, [event.target.name]: event.target.value }) }
  async function handleSubmit(event) { event.preventDefault(); setError(''); setIsSaving(true); const payload = { ...form, requiredSkills: form.requiredSkills.split(',').map((skill) => skill.trim()).filter(Boolean), minimumYearsExperience: Number(form.minimumYearsExperience), salaryMin: form.salaryMin === '' ? null : Number(form.salaryMin), salaryMax: form.salaryMax === '' ? null : Number(form.salaryMax) }; try { const result = jobId ? await updateJob(jobId, payload) : await createJob(payload); navigate(`/recruiter/jobs/${result.id}`) } catch (requestError) { setError(getApiErrorMessage(requestError, 'Unable to save job.')) } finally { setIsSaving(false) } }
  if (isLoading) return <main className="workspace-page"><p className="page-state">Loading job...</p></main>
  return <main className="workspace-page"><Link to="/recruiter/jobs">Back to jobs</Link><p className="eyebrow">{jobId ? 'Edit draft' : 'New draft'}</p><h1>{jobId ? 'Edit job' : 'Create a job'}</h1>{error && <p className="error-message">{error}</p>}<form className="form-grid" onSubmit={handleSubmit}><label>Title<input name="title" value={form.title} onChange={updateField} required /></label><label>Domain<input name="domain" value={form.domain} onChange={updateField} required /></label><label>Location<input name="location" value={form.location || ''} onChange={updateField} /></label><label>Employment type<input name="employmentType" value={form.employmentType || ''} onChange={updateField} /></label><label>Workplace type<input name="workplaceType" value={form.workplaceType || ''} onChange={updateField} /></label><label>Minimum years<input type="number" min="0" max="50" name="minimumYearsExperience" value={form.minimumYearsExperience} onChange={updateField} required /></label><label>Required education<select name="requiredEducationLevel" value={form.requiredEducationLevel} onChange={updateField}>{educationLevels.map((level) => <option key={level}>{level}</option>)}</select></label><label>Required skills<input name="requiredSkills" value={form.requiredSkills} onChange={updateField} placeholder="Java, Spring, SQL" required /></label><label>Minimum salary<input type="number" min="0" name="salaryMin" value={form.salaryMin} onChange={updateField} /></label><label>Maximum salary<input type="number" min="0" name="salaryMax" value={form.salaryMax} onChange={updateField} /></label><label className="full-width">Description<textarea name="description" value={form.description} onChange={updateField} rows="5" required /></label><label className="full-width">Requirements<textarea name="requirements" value={form.requirements || ''} onChange={updateField} rows="4" /></label><button type="submit" disabled={isSaving}>{isSaving ? 'Saving...' : 'Save draft'}</button></form></main>
}

export default RecruiterJobFormPage